/*
 * VitaDrop - frontend.h
 * Embedded HTML/CSS/JS constant for the web interface.
 */

#ifndef FRONTEND_H
#define FRONTEND_H

const char *frontend_html = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>VitaDrop</title>\n"
"    <style>\n"
"        :root {\n"
"            --bg-color: #0f172a;\n"
"            --panel-bg: #1e293b;\n"
"            --text: #f8fafc;\n"
"            --text-muted: #94a3b8;\n"
"            --primary: #3b82f6;\n"
"            --primary-hover: #2563eb;\n"
"            --success: #10b981;\n"
"            --danger: #ef4444;\n"
"            --border: #334155;\n"
"        }\n"
"        * {\n"
"            box-sizing: border-box;\n"
"            margin: 0;\n"
"            padding: 0;\n"
"        }\n"
"        body {\n"
"            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
"            background-color: var(--bg-color);\n"
"            color: var(--text);\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            justify-content: center;\n"
"            min-height: 100vh;\n"
"            padding: 20px;\n"
"        }\n"
"        .container {\n"
"            background-color: var(--panel-bg);\n"
"            border-radius: 16px;\n"
"            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.5);\n"
"            width: 100%;\n"
"            max-width: 500px;\n"
"            padding: 40px 30px;\n"
"            text-align: center;\n"
"            border: 1px solid var(--border);\n"
"        }\n"
"        h1 {\n"
"            font-size: 2.2rem;\n"
"            margin-bottom: 5px;\n"
"            font-weight: 700;\n"
"            background: linear-gradient(135deg, #60a5fa, #a78bfa);\n"
"            -webkit-background-clip: text;\n"
"            -webkit-text-fill-color: transparent;\n"
"        }\n"
"        p.subtitle {\n"
"            color: var(--text-muted);\n"
"            margin-bottom: 30px;\n"
"        }\n"
"        .dropzone {\n"
"            border: 2px dashed var(--border);\n"
"            border-radius: 12px;\n"
"            padding: 40px 20px;\n"
"            cursor: pointer;\n"
"            transition: all 0.2s ease;\n"
"            background-color: rgba(15, 23, 42, 0.4);\n"
"            margin-bottom: 25px;\n"
"            position: relative;\n"
"            overflow: hidden;\n"
"        }\n"
"        .dropzone:hover, .dropzone.dragover {\n"
"            border-color: var(--primary);\n"
"            background-color: rgba(59, 130, 246, 0.1);\n"
"        }\n"
"        .dropzone-icon {\n"
"            font-size: 48px;\n"
"            color: var(--primary);\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        .dropzone-text {\n"
"            font-size: 1.1rem;\n"
"            color: var(--text);\n"
"            font-weight: 500;\n"
"        }\n"
"        .dropzone-subtext {\n"
"            font-size: 0.9rem;\n"
"            color: var(--text-muted);\n"
"            margin-top: 8px;\n"
"        }\n"
"        input[type=\"file\"] {\n"
"            display: none;\n"
"        }\n"
"        .progress-wrapper {\n"
"            display: none;\n"
"            margin-top: 20px;\n"
"            text-align: left;\n"
"        }\n"
"        .progress-info {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            margin-bottom: 8px;\n"
"            font-size: 0.9rem;\n"
"            color: var(--text-muted);\n"
"        }\n"
"        .progress-bar-container {\n"
"            width: 100%;\n"
"            height: 10px;\n"
"            background-color: rgba(255, 255, 255, 0.1);\n"
"            border-radius: 5px;\n"
"            overflow: hidden;\n"
"        }\n"
"        .progress-bar {\n"
"            height: 100%;\n"
"            background: linear-gradient(90deg, var(--primary), #8b5cf6);\n"
"            width: 0%;\n"
"            transition: width 0.1s ease;\n"
"        }\n"
"        .status-message {\n"
"            margin-top: 15px;\n"
"            font-size: 0.95rem;\n"
"            font-weight: 500;\n"
"        }\n"
"        .status-success { color: var(--success); }\n"
"        .status-error { color: var(--danger); }\n"
"        .select-btn {\n"
"            background-color: var(--primary);\n"
"            color: white;\n"
"            border: none;\n"
"            padding: 8px 16px;\n"
"            border-radius: 6px;\n"
"            cursor: pointer;\n"
"            font-size: 0.9rem;\n"
"            margin: 5px;\n"
"            transition: background 0.2s;\n"
"        }\n"
"        .select-btn:hover { background-color: var(--primary-hover); }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>VitaDrop</h1>\n"
"        <p class=\"subtitle\">Send files directly to your PS Vita.</p>\n"
"        \n"
"        <div class=\"dropzone\" id=\"dropzone\">\n"
"            <div class=\"dropzone-icon\">📁</div>\n"
"            <div class=\"dropzone-text\" style=\"margin-bottom:10px;\">Drag Files Here or Select:</div>\n"
"            <div>\n"
"                <button class=\"select-btn\" onclick=\"document.getElementById('fileInput').click(); event.stopPropagation();\">Files</button>\n"
"                <button class=\"select-btn\" onclick=\"document.getElementById('folderInput').click(); event.stopPropagation();\">Folder</button>\n"
"            </div>\n"
"            <div class=\"dropzone-subtext\" style=\"margin-top:15px;\">Saved to ux0:/VitaDrop/</div>\n"
"            <input type=\"file\" id=\"fileInput\" multiple>\n"
"            <input type=\"file\" id=\"folderInput\" multiple webkitdirectory directory>\n"
"        </div>\n"
"        \n"
"        <div class=\"progress-wrapper\" id=\"progressWrapper\">\n"
"            <div class=\"progress-info\">\n"
"                <span id=\"fileName\">Uploading...</span>\n"
"                <span id=\"progressPercent\">0%</span>\n"
"            </div>\n"
"            <div class=\"progress-info\" style=\"margin-top:-3px; margin-bottom:8px;\">\n"
"                <span id=\"speedInfo\" style=\"color:var(--primary); font-weight:600;\">-- MB/s</span>\n"
"                <span id=\"etaInfo\" style=\"color:var(--success);\">ETA: --s</span>\n"
"            </div>\n"
"            <div class=\"progress-bar-container\">\n"
"                <div class=\"progress-bar\" id=\"progressBar\"></div>\n"
"            </div>\n"
"            <div class=\"status-message\" id=\"statusMessage\"></div>\n"
"        </div>\n"
"        <div id=\"historyList\" style=\"margin-top:20px; text-align:left; display:flex; flex-direction:column; gap:8px;\"></div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        const dropzone = document.getElementById('dropzone');\n"
"        const fileInput = document.getElementById('fileInput');\n"
"        const folderInput = document.getElementById('folderInput');\n"
"        const progressWrapper = document.getElementById('progressWrapper');\n"
"        const progressBar = document.getElementById('progressBar');\n"
"        const progressPercent = document.getElementById('progressPercent');\n"
"        const fileNameDisplay = document.getElementById('fileName');\n"
"        const speedInfo = document.getElementById('speedInfo');\n"
"        const etaInfo = document.getElementById('etaInfo');\n"
"        const statusMessage = document.getElementById('statusMessage');\n"
"\n"
"        // Drag & Drop Events\n"
"        ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\n"
"            dropzone.addEventListener(eventName, preventDefaults, false);\n"
"        });\n"
"        function preventDefaults(e) {\n"
"            e.preventDefault();\n"
"            e.stopPropagation();\n"
"        }\n"
"\n"
"        ['dragenter', 'dragover'].forEach(eventName => {\n"
"            dropzone.addEventListener(eventName, () => dropzone.classList.add('dragover'), false);\n"
"        });\n"
"        ['dragleave', 'drop'].forEach(eventName => {\n"
"            dropzone.addEventListener(eventName, () => dropzone.classList.remove('dragover'), false);\n"
"        });\n"
"\n"
"        dropzone.addEventListener('drop', handleDrop, false);\n"
"        // Removed global click on dropzone so individual buttons work natively\n"
"        fileInput.addEventListener('change', (e) => {\n"
"            if (fileInput.files.length) uploadFiles(fileInput.files);\n"
"        });\n"
"        folderInput.addEventListener('change', (e) => {\n"
"            if (folderInput.files.length) uploadFiles(folderInput.files);\n"
"        });\n"
"\n"
"        function handleDrop(e) {\n"
"            const items = e.dataTransfer.items;\n"
"            if (!items || !items.length) return;\n"
"            const fileList = [];\n"
"            let pending = 0;\n"
"            function traverseEntry(entry, path) {\n"
"                if (entry.isFile) {\n"
"                    pending++;\n"
"                    entry.file(f => {\n"
"                        Object.defineProperty(f, '_path', {value: path + f.name});\n"
"                        fileList.push(f);\n"
"                        pending--;\n"
"                        if (pending === 0) uploadFiles(fileList);\n"
"                    });\n"
"                } else if (entry.isDirectory) {\n"
"                    pending++;\n"
"                    const reader = entry.createReader();\n"
"                    reader.readEntries(entries => {\n"
"                        pending--;\n"
"                        for (const sub of entries) traverseEntry(sub, path + entry.name + '/');\n"
"                        if (pending === 0 && fileList.length) uploadFiles(fileList);\n"
"                    });\n"
"                }\n"
"            }\n"
"            for (let i = 0; i < items.length; i++) {\n"
"                const entry = items[i].webkitGetAsEntry ? items[i].webkitGetAsEntry() : null;\n"
"                if (entry) traverseEntry(entry, '');\n"
"                else if (items[i].kind === 'file') {\n"
"                    const f = items[i].getAsFile();\n"
"                    if (f) { Object.defineProperty(f, '_path', {value: f.name}); fileList.push(f); }\n"
"                }\n"
"            }\n"
"            if (pending === 0 && fileList.length) uploadFiles(fileList);\n"
"        }\n"
"\n"
"        async function uploadFiles(files) {\n"
"            progressWrapper.style.display = 'block';\n"
"            \n"
"            for (let i = 0; i < files.length; i++) {\n"
"                await uploadSingleFile(files[i], i + 1, files.length);\n"
"            }\n"
"            \n"
"            setTimeout(() => {\n"
"                progressWrapper.style.display = 'none';\n"
"            }, 1500);\n"
"            \n"
"            fileInput.value = '';\n"
"            folderInput.value = '';\n"
"        }\n"
"\n"
"        function uploadSingleFile(file, currentIndex, totalFiles) {\n"
"            return new Promise((resolve) => {\n"
"                const relativePath = file._path || file.webkitRelativePath || file.name;\n"
"                fileNameDisplay.textContent = `[${currentIndex}/${totalFiles}] ${relativePath}`;\n"
"                progressBar.style.width = '0%';\n"
"                progressPercent.textContent = '0%';\n"
"                statusMessage.textContent = 'Uploading...';\n"
"                statusMessage.className = 'status-message';\n"
"                \n"
"                const xhr = new XMLHttpRequest();\n"
"                xhr.open('POST', '/upload', true);\n"
"                xhr.setRequestHeader('X-File-Name', encodeURIComponent(relativePath));\n"
"                \n"
"                let startTime = Date.now();\n"
"                let lastLoaded = 0;\n"
"                let lastTime = startTime;\n"
"\n"
"                xhr.upload.onprogress = (e) => {\n"
"                    if (e.lengthComputable) {\n"
"                        const percent = Math.round((e.loaded / e.total) * 100);\n"
"                        progressBar.style.width = percent + '%';\n"
"                        progressPercent.textContent = percent + '%';\n"
"\n"
"                        const now = Date.now();\n"
"                        const timeDiff = (now - lastTime) / 1000;\n"
"                        if (timeDiff > 0.2) {\n"
"                            const bytesDiff = e.loaded - lastLoaded;\n"
"                            const speedBps = bytesDiff / timeDiff;\n"
"                            const speedMbps = (speedBps / (1024 * 1024)).toFixed(2);\n"
"                            \n"
"                            const bytesLeft = e.total - e.loaded;\n"
"                            const timeLeftSeconds = Math.round(bytesLeft / speedBps);\n"
"                            \n"
"                            speedInfo.textContent = `${speedMbps} MB/s`;\n"
"                            if (timeLeftSeconds > 0) {\n"
"                                etaInfo.textContent = `ETA: ${timeLeftSeconds}s`;\n"
"                            } else {\n"
"                                etaInfo.textContent = 'Finishing...';\n"
"                            }\n"
"                            \n"
"                            lastLoaded = e.loaded;\n"
"                            lastTime = now;\n"
"                        }\n"
"                    }\n"
"                };\n"
"                \n"
"                xhr.onload = () => {\n"
"                    if (xhr.status === 200) {\n"
"                        statusMessage.textContent = 'Upload complete!';\n"
"                        statusMessage.className = 'status-message status-success';\n"
"                        progressBar.style.width = '100%';\n"
"                        progressPercent.textContent = '100%';\n"
"                        speedInfo.textContent = '0 MB/s';\n"
"                        etaInfo.textContent = '';\n"
"\n"
"                        // Append visually to History logs\n"
"                        const hist = document.getElementById('historyList');\n"
"                        const item = document.createElement('div');\n"
"                        item.style = 'background:var(--surface); padding:12px; border-radius:6px; font-size:0.9rem; border:1px solid var(--border); box-shadow:0 2px 4px rgba(0,0,0,0.2);';\n"
"                        item.innerHTML = `<span style=\"color:var(--success); font-weight:bold; margin-right:8px;\">✓ Completed</span> <span style=\"color:var(--text);\">${relativePath}</span>`;\n"
"                        hist.prepend(item);\n"
"                    } else {\n"
"                        statusMessage.textContent = 'Error: ' + xhr.statusText;\n"
"                        statusMessage.className = 'status-message status-error';\n"
"                    }\n"
"                    resolve();\n"
"                };\n"
"                \n"
"                xhr.onerror = () => {\n"
"                    statusMessage.textContent = 'Network Error';\n"
"                    statusMessage.className = 'status-message status-error';\n"
"                    resolve();\n"
"                };\n"
"                \n"
"                xhr.send(file);\n"
"            });\n"
"        }\n"
"    </script>\n"
"</body>\n"
"</html>\n";

#endif // FRONTEND_H
