/*
 * VitaDrop - frontend.h
 * Embedded HTML/CSS/JS — Full File Manager Interface
 */

#ifndef FRONTEND_H
#define FRONTEND_H

const char *frontend_html =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
"<title>VitaDrop</title>\n"
"<style>\n"
":root{\n"
"  --bg:#0f172a;--surface:#1e293b;--surface2:#293548;\n"
"  --text:#f8fafc;--muted:#94a3b8;--primary:#3b82f6;--primary-h:#2563eb;\n"
"  --ok:#10b981;--err:#ef4444;--warn:#f59e0b;--border:#334155;\n"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;\n"
"  background:var(--bg);color:var(--text);height:100vh;display:flex;flex-direction:column;overflow:hidden}\n"
"a{color:var(--primary);text-decoration:none}\n"
".hdr{background:var(--surface);border-bottom:1px solid var(--border);padding:10px 20px;\n"
"  display:flex;align-items:center;gap:16px}\n"
".logo{font-size:1.4rem;font-weight:700;background:linear-gradient(135deg,#60a5fa,#a78bfa);\n"
"  -webkit-background-clip:text;-webkit-text-fill-color:transparent;white-space:nowrap}\n"
".bc{display:flex;align-items:center;gap:2px;font-size:.85rem;flex:1;overflow-x:auto;white-space:nowrap}\n"
".bc span{color:var(--muted);cursor:pointer;padding:3px 6px;border-radius:4px;transition:.15s}\n"
".bc span:hover{color:var(--text);background:var(--surface2)}\n"
".bc .s{color:var(--border);cursor:default;padding:0 2px}\n"
".bc .s:hover{background:none;color:var(--border)}\n"
".main{display:flex;flex:1;overflow:hidden}\n"
".side{width:180px;background:var(--surface);border-right:1px solid var(--border);\n"
"  padding:14px 0;overflow-y:auto;flex-shrink:0}\n"
".st{font-size:.7rem;text-transform:uppercase;color:var(--muted);padding:0 14px;\n"
"  margin:10px 0 6px;letter-spacing:.06em}\n"
".si{padding:7px 14px;cursor:pointer;display:flex;align-items:center;gap:8px;\n"
"  font-size:.85rem;color:var(--muted);transition:.15s;border-left:3px solid transparent}\n"
".si:hover,.si.a{background:var(--surface2);color:var(--text);border-left-color:var(--primary)}\n"
".cnt{flex:1;display:flex;flex-direction:column;overflow:hidden}\n"
".tb{display:flex;align-items:center;gap:6px;padding:8px 16px;\n"
"  border-bottom:1px solid var(--border);background:var(--surface);flex-wrap:wrap}\n"
".tbtn{background:var(--surface2);border:1px solid var(--border);color:var(--text);\n"
"  padding:5px 12px;border-radius:5px;cursor:pointer;font-size:.8rem;transition:.15s;\n"
"  display:inline-flex;align-items:center;gap:5px}\n"
".tbtn:hover{background:var(--primary);border-color:var(--primary)}\n"
".tbtn.dng:hover{background:var(--err);border-color:var(--err)}\n"
".sp{flex:1}\n"
".fl{flex:1;overflow-y:auto}\n"
".fl.drag{background:rgba(59,130,246,.06);outline:2px dashed var(--primary);outline-offset:-6px}\n"
".fr{display:flex;align-items:center;padding:8px 16px;border-bottom:1px solid rgba(51,65,85,.3);\n"
"  cursor:pointer;transition:background .1s;gap:10px}\n"
".fr:hover{background:var(--surface2)}\n"
".fi{font-size:1.1rem;width:24px;text-align:center;flex-shrink:0}\n"
".fn{flex:1;font-size:.85rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}\n"
".fs{font-size:.75rem;color:var(--muted);width:70px;text-align:right;flex-shrink:0}\n"
".fa{display:flex;gap:4px;opacity:0;transition:opacity .15s;flex-shrink:0}\n"
".fr:hover .fa{opacity:1}\n"
".fab{background:none;border:1px solid var(--border);color:var(--muted);\n"
"  padding:3px 7px;border-radius:3px;cursor:pointer;font-size:.7rem;transition:.15s}\n"
".fab:hover{color:var(--text);background:var(--surface2)}\n"
".fab.dl:hover{color:var(--ok);border-color:var(--ok)}\n"
".fab.rm:hover{color:var(--err);border-color:var(--err)}\n"
".sb{background:var(--surface);border-top:1px solid var(--border);padding:5px 16px;\n"
"  font-size:.75rem;color:var(--muted);display:flex;justify-content:space-between}\n"
".po{display:none;position:fixed;bottom:50px;right:20px;background:var(--surface);\n"
"  border:1px solid var(--border);border-radius:10px;padding:14px 18px;width:340px;\n"
"  box-shadow:0 8px 28px rgba(0,0,0,.5);z-index:100}\n"
".pt{font-size:.82rem;margin-bottom:6px;font-weight:600}\n"
".ps{display:flex;justify-content:space-between;font-size:.78rem;color:var(--muted);margin-bottom:5px}\n"
".pk{height:5px;background:rgba(255,255,255,.08);border-radius:3px;overflow:hidden}\n"
".pf{height:100%;background:linear-gradient(90deg,var(--primary),#8b5cf6);width:0%;transition:width .1s}\n"
".mbg{display:none;position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:200;\n"
"  justify-content:center;align-items:center}\n"
".mbg.show{display:flex}\n"
".mdl{background:var(--surface);border:1px solid var(--border);border-radius:10px;\n"
"  padding:22px;width:360px;box-shadow:0 12px 40px rgba(0,0,0,.5)}\n"
".mdl h3{margin-bottom:14px;font-size:1rem}\n"
".mdl input{width:100%;padding:8px 10px;background:var(--bg);border:1px solid var(--border);\n"
"  border-radius:5px;color:var(--text);font-size:.85rem;margin-bottom:14px;outline:none}\n"
".mdl input:focus{border-color:var(--primary)}\n"
".mbtns{display:flex;justify-content:flex-end;gap:8px}\n"
".mb{padding:7px 14px;border-radius:5px;border:none;cursor:pointer;font-size:.82rem}\n"
".mb.c{background:var(--surface2);color:var(--text)}\n"
".mb.p{background:var(--primary);color:#fff}\n"
".empty{text-align:center;padding:50px 20px;color:var(--muted)}\n"
".empty .ei{font-size:2.5rem;margin-bottom:10px}\n"
"input[type=file]{display:none}\n"
"@media(max-width:640px){.side{display:none}.hdr{padding:8px 12px}.tb{padding:6px 10px}\n"
"  .fr{padding:8px 10px}.po{width:90%;right:5%;bottom:60px}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"hdr\">\n"
"  <div class=\"logo\">VitaDrop</div>\n"
"  <div class=\"bc\" id=\"bc\"></div>\n"
"</div>\n"
"<div class=\"main\">\n"
"  <div class=\"side\">\n"
"    <div class=\"st\">Storage</div>\n"
"    <div class=\"si\" data-p=\"ux0:/\" onclick=\"nav(this.dataset.p)\">&#x1F4BE; ux0:</div>\n"
"    <div class=\"si\" data-p=\"ur0:/\" onclick=\"nav(this.dataset.p)\">&#x2699;&#xFE0F; ur0:</div>\n"
"    <div class=\"si\" data-p=\"uma0:/\" onclick=\"nav(this.dataset.p)\">&#x1F4BF; uma0:</div>\n"
"    <div class=\"st\">Quick Access</div>\n"
"    <div class=\"si\" data-p=\"ux0:/VitaDrop/\" onclick=\"nav(this.dataset.p)\">&#x1F4E5; VitaDrop</div>\n"
"    <div class=\"si\" data-p=\"ux0:/app/\" onclick=\"nav(this.dataset.p)\">&#x1F4E6; Apps</div>\n"
"    <div class=\"si\" data-p=\"ux0:/data/\" onclick=\"nav(this.dataset.p)\">&#x1F4C1; Data</div>\n"
"  </div>\n"
"  <div class=\"cnt\">\n"
"    <div class=\"tb\">\n"
"      <button class=\"tbtn\" onclick=\"document.getElementById('fi').click()\">&#x2B06; Upload Files</button>\n"
"      <button class=\"tbtn\" onclick=\"document.getElementById('di').click()\">&#x1F4C1; Upload Folder</button>\n"
"      <button class=\"tbtn\" onclick=\"showMkdir()\">&#x2795; New Folder</button>\n"
"      <div class=\"sp\"></div>\n"
"      <button class=\"tbtn\" onclick=\"nav(curPath)\">&#x1F504; Refresh</button>\n"
"    </div>\n"
"    <div class=\"fl\" id=\"fl\"></div>\n"
"    <div class=\"sb\"><span id=\"ic\">Loading...</span><span id=\"cp\"></span></div>\n"
"  </div>\n"
"</div>\n"
"<div class=\"po\" id=\"po\">\n"
"  <div class=\"pt\" id=\"ptt\">Uploading...</div>\n"
"  <div class=\"ps\"><span id=\"pfn\"></span><span id=\"ppc\">0%</span></div>\n"
"  <div class=\"ps\"><span id=\"psp\" style=\"color:var(--primary);font-weight:600\">-- MB/s</span>\n"
"    <span id=\"pet\" style=\"color:var(--ok)\"></span></div>\n"
"  <div class=\"pk\"><div class=\"pf\" id=\"pb\"></div></div>\n"
"</div>\n"
"<div class=\"mbg\" id=\"mbg\">\n"
"  <div class=\"mdl\">\n"
"    <h3>New Folder</h3>\n"
"    <input id=\"mni\" placeholder=\"Folder name...\">\n"
"    <div class=\"mbtns\">\n"
"      <button class=\"mb c\" onclick=\"closeMdl()\">Cancel</button>\n"
"      <button class=\"mb p\" onclick=\"doMkdir()\">Create</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"<input type=\"file\" id=\"fi\" multiple>\n"
"<input type=\"file\" id=\"di\" multiple webkitdirectory directory>\n"
"\n"
"<script>\n"
"let curPath='ux0:/';\n"
"const fl=document.getElementById('fl');\n"
"\n"
"function nav(p){\n"
"  if(!p.endsWith('/'))p+='/';\n"
"  curPath=p;\n"
"  document.getElementById('cp').textContent=p;\n"
"  updBC(p);updSide(p);\n"
"  fl.innerHTML='<div class=\"empty\"><div class=\"ei\">&#x23F3;</div>Loading...</div>';\n"
"  fetch('/api/ls?path='+encodeURIComponent(p))\n"
"    .then(r=>{if(!r.ok)throw 0;return r.json()})\n"
"    .then(render)\n"
"    .catch(()=>{fl.innerHTML='<div class=\"empty\"><div class=\"ei\">&#x26A0;&#xFE0F;</div>Cannot read directory</div>';});\n"
"}\n"
"\n"
"function updBC(p){\n"
"  const bc=document.getElementById('bc');\n"
"  const m=p.match(/^([a-z0-9]+:)\\/(.*)/);\n"
"  if(!m){bc.innerHTML='';return;}\n"
"  let h='<span onclick=\"nav(\\''+m[1]+'/\\')\">' +m[1]+'</span>';\n"
"  if(m[2]){\n"
"    const pts=m[2].split('/').filter(x=>x);\n"
"    let acc=m[1]+'/';\n"
"    for(const pt of pts){acc+=pt+'/';h+='<span class=\"s\">/</span><span onclick=\"nav(\\''+acc+'\\')\">' +pt+'</span>';}\n"
"  }\n"
"  bc.innerHTML=h;\n"
"}\n"
"\n"
"function updSide(p){\n"
"  document.querySelectorAll('.si').forEach(s=>{\n"
"    s.classList.toggle('a',p.startsWith(s.dataset.p));\n"
"  });\n"
"}\n"
"\n"
"function render(entries){\n"
"  entries.sort((a,b)=>{\n"
"    if(a.t!==b.t)return a.t==='d'?-1:1;\n"
"    return a.n.toLowerCase().localeCompare(b.n.toLowerCase());\n"
"  });\n"
"  const parts=curPath.match(/^[a-z0-9]+:\\/(.+)/);\n"
"  let h='';\n"
"  if(parts&&parts[1]){\n"
"    const up=curPath.replace(/[^\\/]+\\/$/,'');\n"
"    h+='<div class=\"fr\" ondblclick=\"nav(\\''+up+'\\')\">';\n"
"    h+='<div class=\"fi\">&#x1F519;</div><div class=\"fn\">..</div><div class=\"fs\"></div><div class=\"fa\"></div></div>';\n"
"  }\n"
"  if(entries.length===0&&!h){\n"
"    fl.innerHTML='<div class=\"empty\"><div class=\"ei\">&#x1F4C2;</div>Empty directory</div>';\n"
"    document.getElementById('ic').textContent='0 items';\n"
"    return;\n"
"  }\n"
"  for(const e of entries){\n"
"    const fp=curPath+e.n;\n"
"    const icon=e.t==='d'?'&#x1F4C1;':fIcon(e.n);\n"
"    const sz=e.t==='f'?fmtSz(e.s):'\\u2014';\n"
"    if(e.t==='d'){\n"
"      h+='<div class=\"fr\" ondblclick=\"nav(\\''+fp+'/\\')\">';\n"
"    }else{\n"
"      h+='<div class=\"fr\">';\n"
"    }\n"
"    h+='<div class=\"fi\">'+icon+'</div>';\n"
"    h+='<div class=\"fn\">'+esc(e.n)+'</div>';\n"
"    h+='<div class=\"fs\">'+sz+'</div>';\n"
"    h+='<div class=\"fa\">';\n"
"    if(e.t==='f')h+='<button class=\"fab dl\" onclick=\"event.stopPropagation();dlf(\\''+fp+'\\')\" title=\"Download\">&#x2B07;</button>';\n"
"    h+='<button class=\"fab rm\" onclick=\"event.stopPropagation();del(\\''+fp+'\\',\\''+e.t+'\\')\" title=\"Delete\">&#x2716;</button>';\n"
"    h+='</div></div>';\n"
"  }\n"
"  fl.innerHTML=h;\n"
"  const dc=entries.filter(e=>e.t==='d').length;\n"
"  const fc=entries.filter(e=>e.t==='f').length;\n"
"  document.getElementById('ic').textContent=dc+' folders, '+fc+' files';\n"
"}\n"
"\n"
"function fIcon(n){\n"
"  const e=n.split('.').pop().toLowerCase();\n"
"  const m={png:'&#x1F5BC;',jpg:'&#x1F5BC;',jpeg:'&#x1F5BC;',gif:'&#x1F5BC;',bmp:'&#x1F5BC;',\n"
"    mp3:'&#x1F3B5;',wav:'&#x1F3B5;',ogg:'&#x1F3B5;',flac:'&#x1F3B5;',\n"
"    mp4:'&#x1F3AC;',avi:'&#x1F3AC;',mkv:'&#x1F3AC;',\n"
"    zip:'&#x1F4E6;',rar:'&#x1F4E6;',vpk:'&#x1F4E6;','7z':'&#x1F4E6;',\n"
"    txt:'&#x1F4DD;',cfg:'&#x1F4DD;',ini:'&#x1F4DD;',xml:'&#x1F4DD;',json:'&#x1F4DD;',log:'&#x1F4DD;',\n"
"    bin:'&#x1F4BF;',self:'&#x26A1;',suprx:'&#x26A1;',skprx:'&#x26A1;'};\n"
"  return m[e]||'&#x1F4C4;';\n"
"}\n"
"\n"
"function fmtSz(b){\n"
"  if(b===0)return '0 B';\n"
"  const u=['B','KB','MB','GB'];\n"
"  const i=Math.floor(Math.log(b)/Math.log(1024));\n"
"  return (b/Math.pow(1024,i)).toFixed(i>0?1:0)+' '+u[i];\n"
"}\n"
"\n"
"function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}\n"
"\n"
"function dlf(p){window.open('/api/dl?path='+encodeURIComponent(p),'_blank');}\n"
"\n"
"function del(p,t){\n"
"  if(!confirm('Delete '+p+'?'))return;\n"
"  fetch('/api/delete?path='+encodeURIComponent(p),{method:'POST'}).then(()=>nav(curPath));\n"
"}\n"
"\n"
"function showMkdir(){\n"
"  document.getElementById('mbg').classList.add('show');\n"
"  const inp=document.getElementById('mni');inp.value='';inp.focus();\n"
"}\n"
"function closeMdl(){document.getElementById('mbg').classList.remove('show');}\n"
"function doMkdir(){\n"
"  const n=document.getElementById('mni').value.trim();\n"
"  if(!n)return;closeMdl();\n"
"  fetch('/api/mkdir?path='+encodeURIComponent(curPath+n),{method:'POST'}).then(()=>nav(curPath));\n"
"}\n"
"document.getElementById('mni').addEventListener('keydown',e=>{if(e.key==='Enter')doMkdir();if(e.key==='Escape')closeMdl();});\n"
"\n"
"// Upload\n"
"document.getElementById('fi').addEventListener('change',e=>{if(e.target.files.length)upFiles(e.target.files);});\n"
"document.getElementById('di').addEventListener('change',e=>{if(e.target.files.length)upFiles(e.target.files);});\n"
"\n"
"// DnD on file list\n"
"['dragenter','dragover','dragleave','drop'].forEach(ev=>fl.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();}));\n"
"['dragenter','dragover'].forEach(ev=>fl.addEventListener(ev,()=>fl.classList.add('drag')));\n"
"['dragleave','drop'].forEach(ev=>fl.addEventListener(ev,()=>fl.classList.remove('drag')));\n"
"fl.addEventListener('drop',handleDrop);\n"
"\n"
"function handleDrop(e){\n"
"  const items=e.dataTransfer.items;\n"
"  if(!items||!items.length)return;\n"
"  const list=[];let pend=0;\n"
"  function walk(entry,path){\n"
"    if(entry.isFile){pend++;entry.file(f=>{Object.defineProperty(f,'_path',{value:path+f.name});list.push(f);pend--;if(pend===0)upFiles(list);});}\n"
"    else if(entry.isDirectory){pend++;entry.createReader().readEntries(ents=>{pend--;for(const s of ents)walk(s,path+entry.name+'/');if(pend===0&&list.length)upFiles(list);});}\n"
"  }\n"
"  for(let i=0;i<items.length;i++){\n"
"    const en=items[i].webkitGetAsEntry?items[i].webkitGetAsEntry():null;\n"
"    if(en)walk(en,'');\n"
"    else if(items[i].kind==='file'){const f=items[i].getAsFile();if(f){Object.defineProperty(f,'_path',{value:f.name});list.push(f);}}\n"
"  }\n"
"  if(pend===0&&list.length)upFiles(list);\n"
"}\n"
"\n"
"async function upFiles(files){\n"
"  const po=document.getElementById('po');po.style.display='block';\n"
"  for(let i=0;i<files.length;i++)await upOne(files[i],i+1,files.length);\n"
"  po.style.display='none';\n"
"  nav(curPath);\n"
"  document.getElementById('fi').value='';\n"
"  document.getElementById('di').value='';\n"
"}\n"
"\n"
"function upOne(file,idx,tot){\n"
"  return new Promise(resolve=>{\n"
"    const rp=file._path||file.webkitRelativePath||file.name;\n"
"    document.getElementById('ptt').textContent='Uploading ['+idx+'/'+tot+']';\n"
"    document.getElementById('pfn').textContent=rp;\n"
"    document.getElementById('ppc').textContent='0%';\n"
"    document.getElementById('pb').style.width='0%';\n"
"    document.getElementById('psp').textContent='-- MB/s';\n"
"    document.getElementById('pet').textContent='';\n"
"    const xhr=new XMLHttpRequest();\n"
"    xhr.open('POST','/api/upload',true);\n"
"    xhr.setRequestHeader('X-File-Name',encodeURIComponent(rp));\n"
"    xhr.setRequestHeader('X-Upload-Dir',encodeURIComponent(curPath));\n"
"    let ll=0,lt=Date.now();\n"
"    xhr.upload.onprogress=e=>{\n"
"      if(!e.lengthComputable)return;\n"
"      const pct=Math.round(e.loaded/e.total*100);\n"
"      document.getElementById('pb').style.width=pct+'%';\n"
"      document.getElementById('ppc').textContent=pct+'%';\n"
"      const now=Date.now(),dt=(now-lt)/1000;\n"
"      if(dt>.2){\n"
"        const sp=(e.loaded-ll)/dt;\n"
"        document.getElementById('psp').textContent=(sp/1048576).toFixed(2)+' MB/s';\n"
"        const left=e.total-e.loaded;const eta=Math.round(left/sp);\n"
"        document.getElementById('pet').textContent=eta>0?'ETA: '+eta+'s':'Finishing...';\n"
"        ll=e.loaded;lt=now;\n"
"      }\n"
"    };\n"
"    xhr.onload=()=>resolve();\n"
"    xhr.onerror=()=>resolve();\n"
"    xhr.send(file);\n"
"  });\n"
"}\n"
"\n"
"nav('ux0:/');\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif // FRONTEND_H
